### ISSUE TITLE
OSError: [WinError 998] Invalid access to memory location.

### ISSUE THREAD

**Issue by quinnell** [forza-painter/forza-painter#5]
Game crashes and the import fails with an OSError 998.  

Python 3.10.1 [MSC v.1929 64 bit (AMD64)] on win32

- Steam version
- Game was open
- Had my 500 layer template open in Vinyl Editor (not livery editor)
- All layers ungrouped

`<class 'OSError'>
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Games\Forza\forza-painter-master\main.py", line 219, in <module>
    main(sys.argv)
  File "C:\Users\user\Downloads\Games\Forza\forza-painter-master\main.py", line 207, in main
    draw_memory_shape(pid, shape, i, cLiveryLayerTable, current_livery_count)
  File "C:\Users\user\Downloads\Games\Forza\forza-painter-master\main.py", line 73, in draw_memory_shape
    write_process_memory(pid, current_layer_address + 0x18, pos_data)
  File "C:\Users\user\Downloads\Games\Forza\forza-painter-master\native.py", line 84, in write_process_memory
    kernel32.WriteProcessMemory(hProcess, address, buf, len(buf),
  File "C:\Users\user\Downloads\Games\Forza\forza-painter-master\native.py", line 26, in _check_zero
    raise ctypes.WinError(ctypes.get_last_error())
OSError: [WinError 998] Invalid access to memory location.
`

**Comment by quinnell** [comment]
Resolved with a PC reboot.
